import { ACTIVITY_HEADERS, ACTIVITY_SHEET } from './activityTracking'
import { APP_LOCK_HEADERS, APP_LOCK_SHEET } from './appLockSync'
import { CATEGORIES_HEADERS, CATEGORIES_SHEET } from './categories'
import { CHECKS_HEADERS, CHECKS_SHEET } from './checks'
import { COUNTERPARTIES_HEADERS, COUNTERPARTIES_SHEET } from './counterparties'
import { DANG_HEADERS, DANG_SHEET } from './dang'
import { INSTALLMENTS_HEADERS, INSTALLMENTS_SHEET } from './installments'
import { MONTHLY_BALANCE_HEADERS, MONTHLY_BALANCE_SHEET } from './monthlyBalance'
import { PERIOD_SETTINGS_HEADERS, PERIOD_SETTINGS_SHEET } from './periodSettings'
import { PERSONAL_REMINDERS_HEADERS, PERSONAL_REMINDERS_SHEET } from './personalReminders'
import { RECEIVABLES_HEADERS, RECEIVABLES_SHEET } from './receivables'
import {
  PUSH_SUBS_HEADERS,
  PUSH_SUBS_SHEET,
  REMINDER_LOG_HEADERS,
  REMINDER_LOG_SHEET,
  REMINDERS_HEADERS,
  REMINDERS_SHEET
} from './reminders'
import type { SheetSpec } from './sheets'
import {
  TIMESHEET_ENTRIES_HEADERS,
  TIMESHEET_ENTRIES_SHEET,
  TIMESHEETS_HEADERS,
  TIMESHEETS_SHEET
} from './timesheetRow'
import { TREASURY_HEADERS, TREASURY_SHEET } from './treasury'
import { VEHICLE_DEADLINE_HEADERS, VEHICLE_DEADLINE_SHEET } from './vehicleDeadlines'
import { VEHICLE_EXPENSE_META_HEADERS, VEHICLE_EXPENSE_META_SHEET } from './vehicleExpenseRecords'
import { VEHICLE_HISTORY_HEADERS, VEHICLE_HISTORY_SHEET } from './vehicleHistory'
import { VEHICLE_MECHANIC_HEADERS, VEHICLE_MECHANIC_SHEET } from './vehicleMechanicVisits'
import { VEHICLE_PERIODIC_HEADERS, VEHICLE_PERIODIC_SHEET } from './vehiclePeriodicServices'
import { VEHICLES_HEADERS, VEHICLES_SHEET } from './vehicleProfiles'
import { WALLET_HEADERS, WALLET_SHEET } from './wallet'

export const MODULE_SHEET_SPECS: SheetSpec[] = [
  { sheetName: INSTALLMENTS_SHEET, headers: INSTALLMENTS_HEADERS },
  { sheetName: DANG_SHEET, headers: DANG_HEADERS },
  { sheetName: CHECKS_SHEET, headers: CHECKS_HEADERS },
  { sheetName: RECEIVABLES_SHEET, headers: RECEIVABLES_HEADERS },
  { sheetName: TREASURY_SHEET, headers: TREASURY_HEADERS },
  { sheetName: WALLET_SHEET, headers: WALLET_HEADERS },
  { sheetName: MONTHLY_BALANCE_SHEET, headers: MONTHLY_BALANCE_HEADERS },
  { sheetName: PERIOD_SETTINGS_SHEET, headers: PERIOD_SETTINGS_HEADERS },
  { sheetName: CATEGORIES_SHEET, headers: CATEGORIES_HEADERS },
  { sheetName: COUNTERPARTIES_SHEET, headers: COUNTERPARTIES_HEADERS },
  { sheetName: TIMESHEETS_SHEET, headers: TIMESHEETS_HEADERS },
  { sheetName: TIMESHEET_ENTRIES_SHEET, headers: TIMESHEET_ENTRIES_HEADERS },
  { sheetName: ACTIVITY_SHEET, headers: ACTIVITY_HEADERS },
  { sheetName: REMINDERS_SHEET, headers: REMINDERS_HEADERS },
  { sheetName: PERSONAL_REMINDERS_SHEET, headers: PERSONAL_REMINDERS_HEADERS },
  { sheetName: VEHICLES_SHEET, headers: VEHICLES_HEADERS },
  { sheetName: VEHICLE_PERIODIC_SHEET, headers: VEHICLE_PERIODIC_HEADERS },
  { sheetName: VEHICLE_DEADLINE_SHEET, headers: VEHICLE_DEADLINE_HEADERS },
  { sheetName: VEHICLE_HISTORY_SHEET, headers: VEHICLE_HISTORY_HEADERS },
  { sheetName: VEHICLE_MECHANIC_SHEET, headers: VEHICLE_MECHANIC_HEADERS },
  { sheetName: VEHICLE_EXPENSE_META_SHEET, headers: VEHICLE_EXPENSE_META_HEADERS },
  { sheetName: PUSH_SUBS_SHEET, headers: PUSH_SUBS_HEADERS },
  { sheetName: REMINDER_LOG_SHEET, headers: REMINDER_LOG_HEADERS },
  { sheetName: APP_LOCK_SHEET, headers: APP_LOCK_HEADERS }
]
